BEGIN
  FOR cust IN (SELECT CUSTOMER_ID FROM CUSTOMERS WHERE AGE > 60) LOOP
    UPDATE LOANS
    SET INTEREST_RATE = INTEREST_RATE - 1
    WHERE CUSTOMER_ID = cust.CUSTOMER_ID;
  END LOOP;
  COMMIT;
END;
/
